# Generated by Django 5.1.1 on 2024-10-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
