# Generated by Django 5.1.1 on 2024-10-15 18:19

from django.db import migrations

from items.models import generate_unique_slug


def populate_slug_field(apps, schema_editor):
    """populate slug field for all existing rows."""
    Item = apps.get_model("items", "Item")
    for item in Item.objects.all():
        item.slug = generate_unique_slug(item.title)
        item.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_item_slug"),
    ]

    operations = [
        migrations.RunPython(
            populate_slug_field, reverse_code=migrations.RunPython.noop
        )
    ]
