# Generated by Django 5.1.1 on 2024-10-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0003_auto_20241015_2119"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
